language: python
cache: pip
dist: xenial
os: linux

jobs:
  include:
    # Wagtail 2.7 LTS
    - env: TOXENV=py35-dj2-wt27
      python: 3.5
    - env: TOXENV=py36-dj2-wt27
      python: 3.6
    - env: TOXENV=py37-dj2-wt27
      python: 3.7
    - env: TOXENV=py38-dj2-wt27
      python: 3.8

    - env: TOXENV=py35-dj21-wt27
      python: 3.5
    - env: TOXENV=py36-dj21-wt27
      python: 3.6
    - env: TOXENV=py37-dj21-wt27
      python: 3.7
    - env: TOXENV=py38-dj21-wt27
      python: 3.8

    - env: TOXENV=py35-dj22-wt27
      python: 3.5
    - env: TOXENV=py36-dj22-wt27
      python: 3.6
    - env: TOXENV=py37-dj22-wt27
      python: 3.7
    - env: TOXENV=py38-dj22-wt27
      python: 3.8

    # Wagtail 2.8
    - env: TOXENV=py35-dj21-wt28
      python: 3.5
    - env: TOXENV=py36-dj21-wt28
      python: 3.6
    - env: TOXENV=py37-dj21-wt28
      python: 3.7
    - env: TOXENV=py38-dj21-wt28
      python: 3.8

    - env: TOXENV=py35-dj22-wt28
      python: 3.5
    - env: TOXENV=py36-dj22-wt28
      python: 3.6
    - env: TOXENV=py37-dj22-wt28
      python: 3.7
    - env: TOXENV=py38-dj22-wt28
      python: 3.8

    - env: TOXENV=py36-dj3-wt28
      python: 3.6
    - env: TOXENV=py37-dj3-wt28
      python: 3.7
    - env: TOXENV=py38-dj3-wt28
      python: 3.8

    # Wagtail 2.9
    - env: TOXENV=py35-dj21-wt29
      python: 3.5
    - env: TOXENV=py36-dj21-wt29
      python: 3.6
    - env: TOXENV=py37-dj21-wt29
      python: 3.7
    - env: TOXENV=py38-dj21-wt29
      python: 3.8

    - env: TOXENV=py35-dj22-wt29
      python: 3.5
    - env: TOXENV=py36-dj22-wt29
      python: 3.6
    - env: TOXENV=py37-dj22-wt29
      python: 3.7
    - env: TOXENV=py38-dj22-wt29
      python: 3.8

    - env: TOXENV=py36-dj3-wt29
      python: 3.6
    - env: TOXENV=py37-dj3-wt29
      python: 3.7
    - env: TOXENV=py38-dj3-wt29
      python: 3.8

    # Flake 8
    - env: TOXENV=flake8
      python: 3.8


install:
  - pip install tox
script:
  - tox -e $TOXENV
